name: Build Plugins

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Typecho Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        cd DiguWormhole && zip -q -r DiguWormhole_latest.zip * && mv DiguWormhole_latest.zip ../ && cd -
        cd HiLinks && zip -q -r HiLinks_latest.zip * && mv HiLinks_latest.zip ../ && cd -
        cd Gemini && zip -q -r Gemini_latest.zip * && mv Gemini_latest.zip ../ && cd -
    - name: Upload DiguWormhole
      uses: WebFreak001/deploy-nightly@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/binjoo/typecho-plugins/releases/77482728/assets{?name,label}
        release_id: 77482728
        asset_path: ./DiguWormhole_latest.zip
        asset_name: DiguWormhole_latest.zip
        asset_content_type: application/zip
    - name: Upload HiLinks
      uses: WebFreak001/deploy-nightly@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/binjoo/typecho-plugins/releases/77482728/assets{?name,label}
        release_id: 77482728
        asset_path: ./HiLinks_latest.zip
        asset_name: HiLinks_latest.zip
        asset_content_type: application/zip
    - name: Upload Gemini
      uses: WebFreak001/deploy-nightly@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/binjoo/typecho-plugins/releases/77482728/assets{?name,label}
        release_id: 77482728
        asset_path: ./Gemini_latest.zip
        asset_name: Gemini_latest.zip
        asset_content_type: application/zip